# Découverte de Numpy

### Introduction à Numpy

In [2]:
list_of_list = [["Paris",75],["Lyon",69]]

Avantages des listes python:
* peuvent contenir différents types des données
* peuvent rétrécir et grandir dynamiquement

In [3]:
list = [1, "film", 3]

In [4]:
list.append("série")
print(list)

[1, 'film', 3, 'série']


Inconvénients des lieste Python:
* consomment beaucoup d'énergie
* problèmatiques pour des datasets de moyenne à très grande taille

### Les tableaux avec Numpy

ndarray

In [5]:
import numpy as np

In [11]:
vector = np.array([3, 4, 17, 65])

In [12]:
print(vector)

[ 3  4 17 65]


In [8]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])

In [9]:
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


Exercice 1:

* Créer un vecteur depuis a liste [10, 20, 30]
    * Assigner le résultat à la variable vector

In [13]:
vector = np.array([10, 20, 30])
print(vector)

[10 20 30]


* Créer une matrice depuis la liste des listes suivantes: [[5,10,15],[20,25,30],[35,40,45]]
    * Assigner le résultat à la variable matrix

In [14]:
matrix = np.array([[2, 5, 15], [20, 50, 30], [34, 99, 45]])
print(matrix)

[[ 2  5 15]
 [20 50 30]
 [34 99 45]]


### Taille d'un tableau


In [15]:
np.array(['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'])

array(['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'], dtype='<U15')

In [17]:
np.array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'], ['1986', 'Americas', 'Uruguay', 'Other', '0.5'], ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62']])

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62']], dtype='<U15')

ndarray.shape

In [19]:
vector = np.array([1, 2, 3, 4])
print(vector.shape)

(4,)


In [20]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
print(matrix.shape)

(2, 3)


Exercice 2:

* Créer un vecteur depuis la liste [10, 20, 30]
    * Assigner le résultat à la variable vector

In [23]:
vector = np.array([10, 20, 30])
print(vector)

[10 20 30]


* Créer une matrice depuis la liste des listes suivantes: [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
    * Assigner le résultat à la variable matrix

In [24]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


* Assigner la taille du tableau vector à la variable vector_shape
* Assigner la taille du tableau matrix à la variable matrix_shape
* Affichier les résultats

In [26]:
vector_shape = vactor.shape
matrix_shape = matrix.shape
print(vector_shape)
print(matrix_shape)

(4,)
(3, 3)


### Lire un dataset avec Numpy

In [27]:
# Fonction numpy pour lire un dataset: numpy.genfromtxt()

In [36]:
import numpy as np

world_alcohol = np.genfromtxt("C:/Users/Thierno Barry/Documents/Python Scripts/01.Data Science - Analyse de données avec Python/00. Data/world_alcohol.csv", delimiter=",")

In [40]:
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [35]:
print(world_alcohol)

[[      nan       nan       nan       nan       nan]
 [1.986e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.000e-01]
 ...
 [1.986e+03       nan       nan       nan 2.540e+00]
 [1.987e+03       nan       nan       nan 0.000e+00]
 [1.986e+03       nan       nan       nan 5.150e+00]]


### Les types de données avec Numpy

In [38]:
# bool --> True ou False
# int --> integer
# float
# string

In [39]:
numbers = np.array([1, 2, 3, 4])
numbers.dtype

dtype('int32')

Exercice 3:

* Assigner le type de données de world_alcohol à la variable world_alcohol_dtype
* Afficher world_alcohol_dtype

In [42]:
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)

float64


### Afficher les données correctement

In [47]:
fichier_in = "C:/Users/Thierno Barry/Documents/Python Scripts/01.Data Science - Analyse de données avec Python/00. Data/world_alcohol.csv"
world_alcohol = np.genfromtxt(fichier_in, delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Extraire une valeur depuis un tableau Numpy

In [49]:
vector = np.array([5, 10, 15, 20])
print(vector[0])

5


In [50]:
list_of_lists = [[5, 10, 15], [20, 25, 30]]

In [51]:
first_row = list_of_lists[0]

In [52]:
first_row[2]

15

In [53]:
list_of_lists[0][2]

15

In [56]:
matrix = np.array([[5, 10, 15], [20, 25, 30]])
matrix[1,2]

30

Exercice 4:

* Assigner le nombre de litres de vin bu par un Ivoirien en 1985 à la variable ivoire_1985. Cela correspond à la donnée de la 3e ligne.
* Assigner le nom du pays de la 2e ligne à la variable second_country.

In [59]:
ivoire_1985 = world_alcohol[2,4]
print(ivoire_1985)

1.62


In [58]:
second_country = world_alcohol[1,2]
print(second_country)

Uruguay


### Extraire un vecteur de valeurs depuis un tableau Numpy

In [60]:
vector = np.array([5, 10, 15, 20])

In [61]:
vector[0:3]

array([ 5, 10, 15])

In [63]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
matrix[:,1]

array([10, 25, 40])

In [65]:
matrix[2,:]

array([35, 40, 45])

In [66]:
matrix[1:3,1]

array([25, 40])

Exercice 5:

* Assigner toute la 3e colonne de world_alcohol à la variable countries.
* Assigner l'ensemble de la 5e colonne de world_alcohol à la variable alcohol_consumption.

In [67]:
countries = world_alcohol[:,2]
print(countries)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']


In [68]:
alcohol_consumption = world_alcohol[:,4]
print(alcohol_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


### Extraire un tableau de valeurs depuis un tableau Numpy

In [69]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
matrix[:,0:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [71]:
matrix[1:3,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [72]:
matrix[1:3,0:2]

array([[20, 25],
       [35, 40]])

Exercice 6:

* Assigner toutes les lignes des 2 premières colonnes de world_alcohol à la variable first_two_colomns.
* Assigner les 10 premières lignes de la première colonne de world_alcohol à la variable first_ten_years.
* Assigner les 10 premières lignes de toutes les colonnes de world_alcohol à la variable first_ten_rows.
* Assigner les 20 premières lignes des colonnes d'indice des colonnes d'indice 1 et 2 de world_alcohol à la variable first_twenty_regions.

In [77]:
first_two_colomns = world_alcohol[:,0:2]
print(first_two_colomns)

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [80]:
first_ten_years = world_alcohol[0:10,0:1]
print(first_ten_years)

[['1986']
 ['1986']
 ['1985']
 ['1986']
 ['1987']
 ['1987']
 ['1987']
 ['1985']
 ['1986']
 ['1984']]


In [81]:
first_ten_rows = world_alcohol[0:10,:]
print(first_ten_rows)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]


In [82]:
first_twenty_regions = world_alcohol[0:20,1:3]
print(first_twenty_regions)

[['Western Pacific' 'Viet Nam']
 ['Americas' 'Uruguay']
 ['Africa' "Cte d'Ivoire"]
 ['Americas' 'Colombia']
 ['Americas' 'Saint Kitts and Nevis']
 ['Americas' 'Guatemala']
 ['Africa' 'Mauritius']
 ['Africa' 'Angola']
 ['Americas' 'Antigua and Barbuda']
 ['Africa' 'Nigeria']
 ['Africa' 'Botswana']
 ['Americas' 'Guatemala']
 ['Western Pacific' "Lao People's Democratic Republic"]
 ['Eastern Mediterranean' 'Afghanistan']
 ['Western Pacific' 'Viet Nam']
 ['Africa' 'Guinea-Bissau']
 ['Americas' 'Costa Rica']
 ['Africa' 'Seychelles']
 ['Europe' 'Norway']
 ['Africa' 'Kenya']]
