#Linear Regression Lab

In the previous lesson, we predicted price using just one variable: bedrooms. Now, we want to predict price given a few other features.

Steps:
1. Use the features: **`bedrooms`**, **`bathrooms`**, **`bathrooms_na`**, **`minimum_nights`**, and **`number_of_reviews`** as input to your VectorAssembler.
1. Build a Linear Regression Model
1. Evaluate the **`RMSE`** and the **`R2`**.

## In this lesson you:
 - Build a linear regression model with multiple features
 - Compute various metrics to evaluate goodness of fit

In [8]:
# On importe les librairies dont on aura besoin pour ce tp
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Output_path = 'C:/Users/Thierno Barry/Documents/Machine Learning/00.data/output/'
Iutput_path = 'C:/Users/Thierno Barry/Documents/Machine Learning/00.data/input/'

In [9]:
# Charger le fichier dans un DataFrame Pandas
file_path = Iutput_path+"sf-listings-2019-03-06-clean_delta.csv"
airbnb_df = pd.read_csv(file_path)

In [11]:
# Diviser le DataFrame en ensembles de formation et de test
train_df, test_df = train_test_split(airbnb_df, test_size=0.2, random_state=42)

print(train_df.shape[0])
print(test_df.shape[0])

5716
1430


In [12]:
# Assembler les caractéristiques en un tableau numpy
X_train = np.concatenate([train_df["bedrooms"].values.reshape(-1, 1), 
                           train_df["bathrooms"].values.reshape(-1, 1), 
                           train_df["bathrooms_na"].values.reshape(-1, 1), 
                           train_df["minimum_nights"].values.reshape(-1, 1), 
                           train_df["number_of_reviews"].values.reshape(-1, 1)], axis=1)
y_train = train_df["price"].values

X_test = np.concatenate([test_df["bedrooms"].values.reshape(-1, 1), 
                          test_df["bathrooms"].values.reshape(-1, 1), 
                          test_df["bathrooms_na"].values.reshape(-1, 1), 
                          test_df["minimum_nights"].values.reshape(-1, 1), 
                          test_df["number_of_reviews"].values.reshape(-1, 1)], axis=1)
y_test = test_df["price"].values

In [13]:
display(X_train)
display(y_train)
display(X_test)
display(y_test)

array([[  1. ,   1. ,   0. ,   1. , 266. ],
       [  2. ,   1. ,   0. ,   2. ,   0. ],
       [  1. ,   1.5,   0. ,   2. ,  50. ],
       ...,
       [  4. ,   2. ,   0. ,   3. ,  53. ],
       [  1. ,   1. ,   0. ,   2. ,  40. ],
       [  1. ,   1. ,   0. ,  30. ,   0. ]])

array([119, 500, 190, ..., 495, 149, 164], dtype=int64)

array([[  1.,   1.,   0.,   1.,  22.],
       [  2.,   1.,   0.,   4., 108.],
       [  0.,   1.,   0.,   1.,   1.],
       ...,
       [  1.,   1.,   0.,   3., 280.],
       [  1.,   1.,   0.,  30.,   2.],
       [  0.,   1.,   0.,  30.,   2.]])

array([120, 315, 180, ..., 140, 180,  87], dtype=int64)

In [27]:
# Entraîner un modèle de régression linéaire
lr_model = LinearRegression().fit(X_train, y_train)
m = lr_model.coef_[0]
b = lr_model.coef_[1]
print(f"The formula for the linear regression line is y = {m:.2f}x + {b:.2f}")

The formula for the linear regression line is y = 113.23x + 15.48


In [20]:
# Faire des prédictions sur les données de test
y_pred = lr_model.predict(X_test)
display(y_pred)

array([184.30555802, 271.12526204,  77.13942885, ..., 108.77113183,
       174.78482665,  61.55640091])

In [18]:
# Évaluer les performances du modèle
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
print(f"RMSE is {rmse}")
print(f"R2 is {r2}")

RMSE is 269.1973682800626
R2 is 0.14436849135852725


In [23]:
# Examine the coefficients for each of the variables.
for col, coef in zip(["bedrooms", "bathrooms", "bathrooms_na", "minimum_nights", "number_of_reviews"], lr_model.coef_):
    print(col, coef)

print(f"intercept: {lr_model.intercept_}")

bedrooms 113.2284257415377
bathrooms 15.481356631285463
bathrooms_na -50.26198674407081
minimum_nights -0.5273912813097487
number_of_reviews -0.2886807892698568
intercept: 62.474144291862586
