## Créez vos premiers arrays avec NumPy

In [1]:
import numpy as np

In [2]:
revenus = [1800, 1500, 2200, 3000, 2172]

### Les arrays NumPy

In [3]:
def moyenne(liste):
    return sum(liste)/len(liste)
moyenne(revenus) # => 2134.4

2134.4

In [4]:
np.mean(revenus)

2134.4

In [5]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


### Créez un array NumPy

In [6]:
revenus_array = np.array(revenus)
display(revenus_array)

array([1800, 1500, 2200, 3000, 2172])

### Créez un array monotype

In [7]:
revenus_array.dtype

dtype('int32')

### Sélectionnez des éléments au sein d’un array

Accédez à un seul élément

In [10]:
# pour accéder au 5ème élement
revenus_array[4]

2172

In [11]:
# pour accéder au dernier élément
revenus_array[-1]

2172

In [12]:
# On peut aussi modifier les valeurs
revenus_array[1] = 1900

Accédez à plusieurs éléments contigus
Nous pouvons accéder à un ensemble d'éléments contigus en combinant **`[]`**  et  **`:`** . La syntaxe suit une règle simple : **`nom_array[i:j:p]`** , avec :

* i : l’indice du début ;
* j : l’indice de fin ;
* p : le pas.

In [13]:
revenus_array[0:3]

array([1800, 1900, 2200])

In [14]:
# Les 3 premiers éléments
print(revenus_array[:3])

[1800 1900 2200]


In [15]:
# Les éléments à partir de l’indice 2
print(revenus_array[2:])

[2200 3000 2172]


In [16]:
# Un élément sur deux
print(revenus_array[::2])

[1800 2200 2172]


Accédez à plusieurs éléments selon une condition

In [17]:
revenus_array[revenus_array > 2000]

array([2200, 3000, 2172])

In [18]:
# plusieurs conditions : Et
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]

array([2200, 2172])

In [19]:
# plusieurs conditions : Ou
revenus_array[(revenus_array > 2000) | (revenus_array < 3000)]

array([1800, 1900, 2200, 3000, 2172])

### Utilisez les méthodes d’array

In [21]:
# type de notre array
revenus_array.dtype

dtype('int32')

In [20]:
# dimensions de notre array
revenus_array.shape

(5,)

In [22]:
# calculer la moyenne
revenus_array.mean()

2214.4

In [24]:
# calculer le maximum (ou le minimum) :
display(revenus_array.max())
display(revenus_array.min())

3000

1800

In [26]:
# accéder à l’indice de l’élement minimum (ou maximum) :
display(revenus_array.argmin())
display(revenus_array.argmax())

0

3

In [27]:
# ordonner par ordre croissant :
revenus_array.sort()
print(revenus_array)

[1800 1900 2172 2200 3000]


### TD:
Considérons les revenus mensuels suivants :

In [29]:
liste = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

A partir de ces revenus, créez un array que vous nommerez revenus :

In [30]:
revenus = np.array(liste)
display(revenus)

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

Maintenant, créez un nouvel array `haut_revenus` dans lequel vous sélectionnerez l'ensemble des revenus supérieurs ou égal à 3000€ :

In [31]:
haut_revenus = revenus[revenus>=3000]
display(haut_revenus)

array([3000, 5000])

 <div class="alert alert-warning" role="alert">
  Notez qu'en python vous pouvez utiliser le '_' aka 'underscore' comme <strong>séparateur de milliers</strong>. En effet, '1 000 000' est plus facile à lire que '1000000'.
</div>

In [32]:
haut_revenus = revenus[revenus>=3_000]
haut_revenus

array([3000, 5000])

Il est à présent temps de calculer quelques indicateurs :
- calculez dans un premier temps la somme des revenus **annuelle**. Pour rappel, les revenus listés ci dessus sont mensuels.
- calculez ensuite la moyenne des revenus des 10 clients

In [33]:
# On calcule la somme : 

somme_sum = revenus.sum()
somme_sum

20672

In [34]:
# On multiplie par 12 : 

somme = somme_sum * 12
somme

248064

 <div class="alert alert-info" role="info">
Dans les premiers temps, il est bon de bien <strong>décomposer</strong> son code. Ecrire plusieurs lignes, passer par des "<em>variables intermédiaires</em>" et bien controler le résultat de chaque commande vous permettra d'éviter les <strong>erreurs</strong>, de prendre <strong>confiance</strong> dans votre code et de mieux <strong>maîtriser</strong> vos acquis. 
</div>
 <div class="alert alert-info" role="info">
Dans un second temps, vous pourrez commencer à <strong>factoriser</strong> votre code, c'est à dire le "<em>compresser</em>": écrire plusieurs lignes en une seule, sans passer par des variables intermédiaires.
</div>

In [36]:
# Il était donc possible de faire les 2 opérations en une ligne : 

somme = revenus.sum() * 12
print("La somme des revenus annuelle est :", somme, "€")

La somme des revenus annuelle est : 248064 €


 <div class="alert alert-warning" role="alert">
  Dans certains cas, l'<strong>ordre des opérations</strong> n'a pas d'influence sur le résultat.
</div>

In [37]:
# En effet, on pouvait aussi faire : 

revenus_12 = revenus * 12
revenus_12

array([21600, 18000, 26400, 36000, 26064, 60000, 16800, 14400, 13200,
       15600])

In [38]:
somme = revenus_12.sum()
somme

248064

Enfin, en général, on note les "grosses" sommes en K€ ou en M€. Cela est plus facile à lire. De plus, votre interlocuteur retiendra plus volontier l'ordre de grandeur d'un chiffre ou même un chiffre 'rond' qu'un chiffre trop détaillé...

In [39]:
# Par exemple : 

somme_K = round(somme / 1000)
print("La somme des revenus annuelle est :", somme_K, "K€")
# Voire même : 

print("La somme des revenus annuelle est d'environ:", 250, "K€")
# Ou encore : 

somme_M = round(somme / 1_000_000,2)
print("La somme des revenus annuelle est :", somme_M, "M€")

La somme des revenus annuelle est : 248 K€
La somme des revenus annuelle est d'environ: 250 K€
La somme des revenus annuelle est : 0.25 M€


Passons à la moyenne

In [40]:
moyenne = revenus.mean()
print("La moyenne des revenus mensuelle est :", moyenne, "€")
# Ou encore : 

moyenne = round(moyenne)
print("La moyenne des revenus mensuelle est :", moyenne, "€")

La moyenne des revenus mensuelle est : 2067.2 €
La moyenne des revenus mensuelle est : 2067 €


Un de nos clients (dont les revenus mensuels s'élevaient jusque là à 1400€) vient de nous annoncer qu'il venait d'obtenir une promotion. Grâce à cette dernière, il a gagné 200€ sur son salaire mensuel. Effectuez cette modification au sein de votre array revenus.

In [41]:
print("Array avant :", revenus)

revenus[revenus == 1400] = 1600
print("Array après :", revenus)

Array avant : [1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]
Array après : [1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]


La modification a bien été effectuée. 

Pour expliciter un peu plus cette ligne de code :
- `revenus[revenus == 1400]` vient sélectionner l'ensemble des éléments qui sont strictement égals à 1400€ (donc ici le seul qui nous intéresse)
- la suite vient modifier cet élement par la nouvelle valeur (ici 1600)

Dans le cas de cette opération on pouvait utiliser également l'opérateur '+=' en écrivant `revenus[revenus == 1400] += 200`

## Transformez vos données en tableaux

### Créez un tableau avec NumPy

In [43]:
tab1 = np.array([[1, 2],
    [3, 4],
    [5, 6]])

tab2 = np.array([[1, 2, 3],
        [4, 5, 6]])

In [44]:
display(tab1)
display(tab2)

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
# un tableau de 3x5 rempli de 1
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
# un tableau de 4 lignes et de 4 colonnes contenant que des 0
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
# un tableau de 6x3 rempli de valeurs aléatoires comprises entre 0 et 1
np.random.random((6, 3))

array([[0.21425172, 0.02435898, 0.13401056],
       [0.57053041, 0.05126319, 0.87457361],
       [0.35902631, 0.39402162, 0.37521248],
       [0.79595166, 0.34271027, 0.33993399],
       [0.81529507, 0.13265156, 0.42986482],
       [0.51395368, 0.54324828, 0.64636138]])

In [48]:
# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises entre 1 et 10
np.random.randint(1, 10, size=(3, 3))

array([[1, 7, 9],
       [9, 3, 3],
       [8, 6, 6]])

### Découvrez l’analogie entre les arrays et les matrices

In [49]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])
C = np.array([[2, 4, 6], [8, 10, 12]])

A+B

array([[ 6, 12],
       [18, 24]])

### TD: 

In [50]:
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,
           yohann, anne, thibault, emmanuel]

display(tableau)

[[1800, 21, 0],
 [1500, 54, 2],
 [2200, 28, 3],
 [3000, 37, 1],
 [2172, 37, 2],
 [5000, 32, 0],
 [1400, 23, 0],
 [1200, 25, 1],
 [1100, 19, 0],
 [1300, 31, 2]]

A partir de cette liste, créez un array que vous nommerez `data` : 

In [52]:
data = np.array(tableau)
display(data)

array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2]])

Paul souhaiterait contracter un prêt immobilier :
- affichez les informations qui lui sont relatives. Pour rappel, Paul correspond à la 5ème ligne de nos données
- calculez ses mensualités maximales, en sachant que le taux d'endettement maximum est de 35% (il ne pourra donc pas rembourser par mois plus de 35% de son revenu).

In [53]:
print("Informations de Paul :")
print(data[4, :])
print("-")
print("Ses mensualités maximales sont de :", round(data[4,0]*0.35, 2), "€")

Informations de Paul :
[2172   37    2]
-
Ses mensualités maximales sont de : 760.2 €


*Paul étant notre 5ème client, l'indice pour accéder aux éléments le concernant est donc 4. Dans un premier temps, on souhaite accéder à toutes ses informations (toutes ses variables) : nous pouvons donc utiliser l'opérateur `:`. Ensuite, pour faire le calcule à partir de ses revenus, on accéder uniquement à la colonne correspondante*

Un nouveau client vient d'arriver, dont les informations sont les suivantes : 

In [54]:
louise = [1900, 31, 1]

Ajoutez ces informations à la suite de votre array 

In [55]:
data = np.vstack((data, louise))

Stockez enfin l'ensemble des informations de salaire de notre clientèle dans une variable `revenus` :

In [56]:
revenus = data[:, 0]
print(revenus)

[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300 1900]


In [57]:
a = np.linspace(5, 10, 11)
print(a[-3:-1])

[9.  9.5]


In [58]:
a[a % 2 == 0]

array([ 6.,  8., 10.])

In [62]:
b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])

display(b)

array([[[ 1,  2],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]])

In [63]:
display(b.shape)

(3, 2, 2)

In [65]:
b = b.reshape([4,1,3])
display(b.shape)

(4, 1, 3)

In [71]:
b = np.array([[[1, 2],[4, 5]],
        [[6, 7],[8, 9]],
        [[10, 11],[12, 13]]])

display(b[2, :,:])

array([[10, 11],
       [12, 13]])

In [73]:
display(np.arange(0,8))

array([0, 1, 2, 3, 4, 5, 6, 7])