# Analyse de données avec Numpy

### Objectif

In [52]:
import numpy as np

fichier_in = "C:/Users/Thierno Barry/Documents/Python Scripts/01.Data Science - Analyse de données avec Python/00. Data/world_alcohol.csv"
world_alcohol = np.genfromtxt(fichier_in, delimiter=",", dtype="U75", skip_header=1)
world_alcohol

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ...,
       ['1986', 'Europe', 'Switzerland', 'Spirits', '2.54'],
       ['1987', 'Western Pacific', 'Papua New Guinea', 'Other', '0'],
       ['1986', 'Africa', 'Swaziland', 'Other', '5.15']], dtype='<U75')

### Effectuer des conparaisons

In [2]:
vector = np.array([5, 10, 15, 20])

In [3]:
vector == 10

array([False,  True, False, False])

In [4]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [5]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

#### Mission:
- Extraire la 3e colonne de world_alcohol et comparer la au pays "Canada". Assigner le résultat à la variable countries_canada.
- Extraire la première colonne de world_alcohol et comparer la à la chaine de caractères "1984". Assigner le résultat à la variable years_1984.

In [7]:
countries_is_canada = world_alcohol[:,2] == "Canada"
countries_canada = world_alcohol[countries_is_canada]
print(countries_canada)

[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1989' 'Americas' 'Canada' 'Wine' '1.27']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1985' 'Americas' 'Canada' 'Beer' '4.94']
 ['1987' 'Americas' 'Canada' 'Wine' '1.3']
 ['1987' 'Americas' 'Canada' 'Beer' '4.83']
 ['1986' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1985' 'Americas' 'Canada' 'Spirits' '3.21']
 ['1985' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1984' 'Americas' 'Canada' 'Wine' '1.24']
 ['1989' 'Americas' 'Canada' 'Spirits' '2.91']
 ['1984' 'Americas' 'Canada' 'Other' '']
 ['1985' 'Americas' 'Canada' 'Wine' '1.29']
 ['1987' 'Americas' 'Canada' 'Spirits' '2.99']
 ['1989' 'Americas' 'Canada' 'Beer' '4.82']
 ['1989' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']
 ['1987' 'Americas' 'Canada' 'Other' '']]


In [8]:
years_is_1984 = world_alcohol[:,0] == "1984"
years_1984 = world_alcohol[years_is_1984]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


### Sélectionner des éléments

In [9]:
vector = np.array([5, 10, 15, 20])
equal_to_ten = [vector == 10]
print(vector[equal_to_ten])

[10]


C:\Users\THIERN~1\AppData\Local\Temp/ipykernel_4100/3012035452.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(vector[equal_to_ten])


In [10]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
second_column_25 = (matrix[:,1] == 25)
print(matrix[second_column_25])

[[20 25 30]]


#### Mission:
- Comparer la 3e colonne de world_alcohol à la chaine de caractères "Algeria".
- Assigner le résultat à la variable country_is_algeria.
- Sélectionner seulement les lignes de world_alcohol pour lesquelles country_is_algeria vaut True
- Assigner le résultat à la variable country_algeria.
- Afficher les résultat

- Faire le même travail pour récupérer toutes les lignes correspondantes à l'année "1984". Assigner le résultat à la variable years_1984.

In [12]:
country_is_algeria = (world_alcohol[:,2] == "Algeria")
country_algeria = world_alcohol[country_is_algeria]
print(country_algeria)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Beer' '0.17']
 ['1987' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1986' 'Africa' 'Algeria' 'Wine' '0.1']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Beer' '0.16']
 ['1989' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1989' 'Africa' 'Algeria' 'Wine' '0.23']
 ['1986' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1985' 'Africa' 'Algeria' 'Beer' '0.19']
 ['1985' 'Africa' 'Algeria' 'Other' '0']
 ['1986' 'Africa' 'Algeria' 'Beer' '0.18']
 ['1985' 'Africa' 'Algeria' 'Wine' '0.11']
 ['1986' 'Africa' 'Algeria' 'Other' '0']
 ['1989' 'Africa' 'Algeria' 'Other' '0']
 ['1987' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']
 ['1985' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1987' 'Africa' 'Algeria' 'Wine' '0.1']]


In [13]:
years_is_1984 = (world_alcohol[:,0] == "1984")
years_1984 = world_alcohol[years_is_1984]
print(years_1984)

[['1984' 'Africa' 'Nigeria' 'Other' '6.1']
 ['1984' 'Eastern Mediterranean' 'Afghanistan' 'Other' '0']
 ['1984' 'Americas' 'Costa Rica' 'Wine' '0.06']
 ...
 ['1984' 'Europe' 'Latvia' 'Spirits' '7.5']
 ['1984' 'Africa' 'Angola' 'Wine' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Wine' '0.46']]


### Effectuer des comparaisons avec plusieurs conditions 

In [14]:
vector

array([ 5, 10, 15, 20])

In [15]:
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [16]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


#### Mission:
- Sélectionner les lignes dont le pays est "Algeria" et l'année "1986":
>- Créer cette double comparaison et assigner le résultat à la variable is_algeria_and_1986.
>- Utiliser is_algeria_and_1986 pour sélectionner les lignes correspondantes dans le tableau world_alcohol.
>- Assigner le résultat à la variable rows_with_algeria_and_1986.
>- Afficher le résultat.

In [17]:
is_algeria_and_1986 = (world_alcohol[:,2] == "Algeria") & (world_alcohol[:,0] == "1984")
rows_with_algeria_and_1986 = world_alcohol[is_algeria_and_1986]
print(rows_with_algeria_and_1986)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']]


### Remplacer des valeurs dans un tableau Numpy

In [18]:
vector = np.array([5, 10, 15, 20])

In [19]:
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [20]:
vector[equal_to_ten_or_five] = 50
print(vector)

[50 50 15 20]


In [21]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
second_column_25 = (matrix[:,1] == 25)
print(second_column_25)

[False  True False]


In [23]:
matrix[second_column_25,1] = 10
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


#### Mission:
- Créer un tableau numpy world_alcohol_2 égal world_alcohol pour le dupliquer sous un autre nom.
- Remplacer toutes les années "1986" de la première colonne de world_alcohol_2 par "2018".
- Remplacer tous les alcools "Wine" de la 4e colonne de world_alcohol_2 par "Beer".

In [24]:
world_alcohol_2 = world_alcohol

In [25]:
print(world_alcohol_2[world_alcohol_2[:,0] == "1986"])

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ...
 ['1986' 'Western Pacific' 'Fiji' 'Spirits' '0.05']
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [26]:
years_is_1986 = (world_alcohol_2[:,0] == "1986")
world_alcohol_2[years_is_1986,0] = "2018"
# ou : world_alcohol_2[:,0][world_alcohol_2[:,0] == "1986"] = "2018"

print(world_alcohol_2[world_alcohol_2[:,0] == "2018"])

[['2018' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['2018' 'Americas' 'Uruguay' 'Other' '0.5']
 ['2018' 'Americas' 'Colombia' 'Beer' '4.27']
 ...
 ['2018' 'Western Pacific' 'Fiji' 'Spirits' '0.05']
 ['2018' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['2018' 'Africa' 'Swaziland' 'Other' '5.15']]


In [27]:
years_is_1986 = (world_alcohol_2[:,3] == "Wine")
world_alcohol_2[years_is_1986,3] = "Beer"
# ou : world_alcohol_2[:,][world_alcohol_2[:,3] == "Wine"] = "Beer"

print(world_alcohol_2[world_alcohol_2[:,3] == "Beer"])

[['2018' 'Western Pacific' 'Viet Nam' 'Beer' '0']
 ['1985' 'Africa' "Cte d'Ivoire" 'Beer' '1.62']
 ['2018' 'Americas' 'Colombia' 'Beer' '4.27']
 ...
 ['1989' 'Europe' 'Poland' 'Beer' '2.03']
 ['1984' 'Africa' 'Angola' 'Beer' '0.57']
 ['1984' 'Africa' 'Central African Republic' 'Beer' '0.46']]


### Remplacer des valeurs dans un tableau Numpy

#### Mission:
- Comparer tous les éléments de la 5e colonne de world_alcohol avec la chaine de caractères vides c'est à dire ''. Assigner le résultat à la variable is_value_empty.
- Sélectionner toutes les valeurs de la 5e colonne de world_alcohol pour lesquelles is_value_empty est égal à True et enfin les remplacer par la chaine de caractères '0'.

In [28]:
is_value_empty = (world_alcohol_2[:,4] == "")
print(world_alcohol_2[is_value_empty])

[['1985' 'Africa' 'Comoros' 'Other' '']
 ['2018' 'Europe' 'Italy' 'Other' '']
 ['1985' 'Europe' 'Lithuania' 'Other' '']
 ...
 ['1984' 'Europe' 'Czech Republic' 'Other' '']
 ['1987' 'Americas' 'Canada' 'Other' '']
 ['2018' 'Europe' 'Poland' 'Other' '']]


In [29]:
world_alcohol_2[is_value_empty,4] = "0"
print(world_alcohol_2[is_value_empty])

[['1985' 'Africa' 'Comoros' 'Other' '0']
 ['2018' 'Europe' 'Italy' 'Other' '0']
 ['1985' 'Europe' 'Lithuania' 'Other' '0']
 ...
 ['1984' 'Europe' 'Czech Republic' 'Other' '0']
 ['1987' 'Americas' 'Canada' 'Other' '0']
 ['2018' 'Europe' 'Poland' 'Other' '0']]


### Convertir des types de données

In [30]:
# astype()

In [31]:
vector = np.array(["1", "2", "3"])

In [32]:
vector = vector.astype(float)

In [33]:
vector

array([1., 2., 3.])

#### Mission:
- Extraire la 5e colonne de world_alcohol et assigner le résultat à la variable alcohol_consumption.
- Utiliser la méthode astype() pour convertir alcohol_consumption en décimal (float).

In [34]:
alcohol_consumption = world_alcohol_2[:,4]
print(alcohol_consumption)

['0' '0.5' '1.62' ... '2.54' '0' '5.15']


In [35]:
alcohol_consumption = alcohol_consumption.astype(float)
print(alcohol_consumption)

[0.   0.5  1.62 ... 2.54 0.   5.15]


### Réaliser des calculs mathématiques avec Numpy

In [36]:
# sum()
# mean()
# max()

In [37]:
vector = np.array([5, 10, 15, 20])
vector

array([ 5, 10, 15, 20])

In [38]:
vector.sum()

50

In [39]:
vector.mean()

12.5

In [40]:
vector.max()

20

In [41]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [43]:
matrix.sum(axis=0)

array([60, 75, 90])

#### Mission:
- Utiliser la méthode sum() pour calculer la somme des valeurs de alcohol_consumption. Assigner le résultat à la variable total_alcohol.
- Utiliser la méthode mean() pour calculer la moyenne des valeurs de alcohol_consumption. Assigner le résultat à la variable average_alcohol.
- Afficher les résultats.

In [44]:
total_alcohol = alcohol_consumption.sum()
average_alcohol = alcohol_consumption.mean()

In [45]:
total_alcohol

3908.96

In [46]:
average_alcohol

1.2001719373656738

### Calculer la consommation totale annuelle par habitant pour un pays donné

#### Mission:
- Créer une matrice qu'on nommera canada_1986 qui contient toutes les lignes de world_alcohol correspondant à l'année "1986" et au pays "Canada".
- Extraire la 5e colonne de canada_1986, remplacer tout chaine de caractères vides ('') par '0' et convertir la colonne en décimal (float). Assigner le résultat à la variable canada_alcohol.
- Calculer la somme de canada_alcohol. Assigner le résultat à la variable total_canadian_drinking.
- Afficher le résultat.

In [53]:
canada_1986 = world_alcohol[(world_alcohol[:,2] == "Canada") & (world_alcohol[:,0] == "1986")]
print(canada_1986)

# ou: is_canada_1986 = (world_alcohol[:,2] == "Canada") & (world_alcohol[:,0] == "1986")
#     canada_1986 = world_alcohol[is_canada_1986,:]
#     print(canada_1986)

[['1986' 'Americas' 'Canada' 'Other' '']
 ['1986' 'Americas' 'Canada' 'Spirits' '3.11']
 ['1986' 'Americas' 'Canada' 'Beer' '4.87']
 ['1986' 'Americas' 'Canada' 'Wine' '1.33']]


In [54]:
canada_alcohol = canada_1986[:,4]
print(canada_alcohol)

['' '3.11' '4.87' '1.33']


In [55]:
is_value_empty = (canada_alcohol == "")
canada_alcohol[is_value_empty] = "0"
canada_alcohol = canada_alcohol.astype(float)
print(canada_alcohol)

# ou: empty_strings = canada_alcohol == ''
#     canada_alcohol[empty_strings] = "0"
#     canada_alcohol = canada_alcohol.astype(float)
#     print(canada_alcohol)

[0.   3.11 4.87 1.33]


In [56]:
total_canadian_drinking = canada_alcohol.sum()
print(total_canadian_drinking)

9.31


### Calculer la consommation pour chaque pays

- Tout d'abord, on crée un dictionnaire vide qui va contenir tous les pays et leurs consommations d'alcool associées, on le nommera totals.
- Sélectionner ensuite les lignes de world_alcohol correspondant à l'année donnée, disons 1989. Assigner le résultat à la variable year.
- Sélectionner dans une liste qu'on nommera countries tous les pays.
- Parcourir tous les pays de la liste à l'aide d'une boucle. Pour chaque pays:
>- Sélectionner les lignes de year correpondant à ce pays
>- Assigner le résultat à la variable country_consumption
>- Extraire la 5e colonne de country_consumption
>- Remplacer toute chaine de caractère vide dans cette colonne par 0
>- Convertir la colonne en décimal (float)
>- Calculer la somme de la colonne
>- Ajouter la somme au dictionnaire totals, avec comme clé le nom du pays et en valeur cette somme.
- Afficher le dictionnaire totals.

In [58]:
totals = {}

is_year = world_alcohol[:,0] == "1989"
year = world_alcohol[is_year,:]
countries = world_alcohol[:,2]

for country in countries:
    is_country = year[:,2] == country
    country_consumption = year[is_country,:]
    alcohol_column = country_consumption[:,4]
    is_empty = alcohol_column == ''
    alcohol_column[is_empty] = "0"
    alcohol_column = alcohol_column.astype(float)
    totals[country] = alcohol_column.sum()
    
print(totals)

{'Viet Nam': 0.16, 'Uruguay': 7.4399999999999995, "Cte d'Ivoire": 2.2, 'Colombia': 6.960000000000001, 'Saint Kitts and Nevis': 4.65, 'Guatemala': 2.47, 'Mauritius': 3.54, 'Angola': 2.28, 'Antigua and Barbuda': 4.69, 'Nigeria': 6.74, 'Botswana': 4.63, "Lao People's Democratic Republic": 5.95, 'Afghanistan': 0.0, 'Guinea-Bissau': 2.67, 'Costa Rica': 5.3999999999999995, 'Seychelles': 3.3000000000000003, 'Norway': 5.08, 'Kenya': 2.82, 'Myanmar': 0.16, 'Romania': 8.41, 'Turkey': 0.72, 'Comoros': 0.10999999999999999, 'Tunisia': 0.95, 'United Kingdom of Great Britain and Northern Ireland': 9.99, 'Bahrain': 4.89, 'Italy': 10.899999999999999, 'Sierra Leone': 4.380000000000001, 'Micronesia (Federated States of)': 0.0, 'Mauritania': 0.02, 'Russian Federation': 5.35, 'Egypt': 0.42000000000000004, 'Sweden': 7.47, 'Qatar': 1.4500000000000002, 'Burkina Faso': 3.99, 'Austria': 13.9, 'Czech Republic': 13.009999999999998, 'Ukraine': 5.32, 'China': 3.33, 'Lithuania': 0.0, 'Zimbabwe': 4.92, 'Trinidad and 

### Trouver le pays qui consomme le plus d'alcool

- Créer une variable highest_value qui gardera en mémoire la plus grande valeur du dictionnaire totals. On la fixe à 0 pour commencer.
- Créer une variable similaire qu'on nommera highest_key qui gardera en mémoire le nom du pays associé à la plus grande valeur. On la fixe à la valeur None.
- Parcourir chaque pays du dictionnaire totals:
>- Si la valeur associée au pays est plus grande que highest_value, assigner la valeur en question à la variable highest_value et assigner la clé correspondante (nom du pays) à la variable highest_key.
- Afficher le pays qui consomme le plus d'alcool (variable highest_key)

In [60]:
highest_value = 0
highest_key = None

for country in totals:
    consumption = totals[country]
    if highest_value < consumption:
        highest_value = consumption
        highest_key = country
        
print(highest_key)

Hungary


In [61]:
print(highest_value)

16.29


In [62]:
def total_dic(year):

    totals = {}

    is_year = (world_alcohol[:,0] == year)
    year = world_alcohol[is_year,:]
    countries = year[:,2]


    for country in countries:
        is_country = year[:,2] == country
        country_consumption = year[is_country,:]
        alcohol_column = country_consumption[:,4]
        is_empty_country_consumption = alcohol_column == ''
        alcohol_column[is_empty_country_consumption] = "0"
        alcohol_column = alcohol_column.astype(float)
        totals[country] = alcohol_column.sum() 
    
    return totals

total_1989 = total_dic("1989")

total_1989

{'Guatemala': 2.47,
 'Seychelles': 3.3000000000000003,
 'Costa Rica': 5.3999999999999995,
 'Mauritius': 3.54,
 'Zimbabwe': 4.92,
 'Suriname': 3.67,
 'Croatia': 10.92,
 'Syrian Arab Republic': 0.54,
 'Bolivia (Plurinational State of)': 3.05,
 'Somalia': 0.0,
 'Namibia': 0.24,
 'Uganda': 7.8,
 'Afghanistan': 0.0,
 'Jamaica': 3.03,
 'Finland': 9.419999999999998,
 'Iraq': 0.75,
 'Malawi': 1.02,
 'Bulgaria': 11.43,
 'Nicaragua': 2.5,
 'Central African Republic': 2.5199999999999996,
 'Burundi': 8.159999999999998,
 'Sweden': 7.47,
 'Greece': 10.15,
 'Kyrgyzstan': 4.279999999999999,
 'Belgium': 11.61,
 'Angola': 2.28,
 'Burkina Faso': 3.99,
 'Czech Republic': 13.009999999999998,
 'United Arab Emirates': 4.43,
 'Peru': 4.99,
 'Trinidad and Tobago': 4.68,
 'Guyana': 9.940000000000001,
 'Bahrain': 4.89,
 'Benin': 1.3800000000000001,
 'Liberia': 5.61,
 'Viet Nam': 0.16,
 'Belarus': 7.9799999999999995,
 'Swaziland': 6.68,
 'France': 16.05,
 'United States of America': 9.16,
 'Cabo Verde': 2.79,
 'S

In [63]:
total_1987 = total_dic("1987")
total_1987

{'Saint Kitts and Nevis': 3.18,
 'Guatemala': 2.78,
 'Mauritius': 3.42,
 'Botswana': 4.26,
 'Guinea-Bissau': 2.4499999999999997,
 'Viet Nam': 0.16,
 'Egypt': 0.39,
 'Qatar': 1.42,
 'Burkina Faso': 4.069999999999999,
 'Austria': 13.5,
 'Trinidad and Tobago': 4.349999999999999,
 'Nicaragua': 3.45,
 'Finland': 8.75,
 'Iran (Islamic Republic of)': 0.0,
 'Suriname': 3.4800000000000004,
 'Iraq': 0.66,
 'Mauritania': 0.02,
 'Ireland': 10.98,
 'Lebanon': 3.8099999999999996,
 'Madagascar': 1.3299999999999998,
 'Chile': 9.49,
 'Ghana': 1.28,
 'Portugal': 13.22,
 'Bahrain': 5.5600000000000005,
 'Paraguay': 7.35,
 'Zimbabwe': 5.029999999999999,
 'Namibia': 0.25,
 'Israel': 2.26,
 'Antigua and Barbuda': 3.68,
 'Swaziland': 3.4699999999999998,
 'Costa Rica': 4.2299999999999995,
 'Belgium': 13.16,
 'Ukraine': 4.01,
 'Peru': 6.680000000000001,
 'Chad': 0.30000000000000004,
 'Ecuador': 2.54,
 'Sudan': 0.25,
 'Gambia': 1.9600000000000002,
 'Philippines': 4.42,
 'United States of America': 9.61,
 'Hondur

In [64]:
def dict_compare(d1, d2):
    d1_keys = set(d1.keys())
    d2_keys = set(d2.keys())
    intersect_keys = d1_keys.intersection(d2_keys)
    added = d1_keys - d2_keys
    removed = d2_keys - d1_keys
    modified = {o : (d1[o], d2[o]) for o in intersect_keys if d1[o] != d2[o]}
    same = set(o for o in intersect_keys if d1[o] == d2[o])
    return added, removed, modified, same

In [65]:
dict_compare(total_1987, total_1989)

(set(),
 set(),
 {'Cyprus': (8.870000000000001, 9.29),
  'Slovenia': (16.64, 12.969999999999999),
  'Tunisia': (0.98, 0.95),
  'Comoros': (0.08, 0.10999999999999999),
  'Russian Federation': (4.59, 5.35),
  'Fiji': (1.6500000000000001, 1.9600000000000002),
  'Kiribati': (0.63, 0.48),
  'Jordan': (0.30000000000000004, 0.19),
  'Croatia': (13.51, 10.92),
  'Romania': (7.08, 8.41),
  'Equatorial Guinea': (2.4, 6.49),
  'Honduras': (2.01, 2.15),
  'Botswana': (4.26, 4.63),
  'Somalia': (0.02, 0.0),
  'Iceland': (5.6499999999999995, 5.359999999999999),
  'Bhutan': (0.46, 0.31),
  'United Kingdom of Great Britain and Northern Ireland': (9.530000000000001,
   9.99),
  'Lesotho': (2.1, 2.02),
  'Costa Rica': (4.2299999999999995, 5.3999999999999995),
  'Belize': (4.6499999999999995, 0.0),
  'Italy': (11.790000000000001, 10.899999999999999),
  "Lao People's Democratic Republic": (4.59, 5.95),
  'Togo': (2.6499999999999995, 2.2199999999999998),
  'Bahamas': (14.139999999999999, 12.290000000000001

In [67]:
d1 = set(total_1989.keys())

In [68]:
d2 = set(total_1987.keys())

In [69]:
intersect_keys = d1.intersection(d2)

In [70]:
intersect_keys

{'Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Antigua and Barbuda',
 'Argentina',
 'Australia',
 'Austria',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia (Plurinational State of)',
 'Botswana',
 'Brazil',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Costa Rica',
 'Croatia',
 "Cte d'Ivoire",
 'Cuba',
 'Cyprus',
 'Czech Republic',
 "Democratic People's Republic of Korea",
 'Democratic Republic of the Congo',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran (Islami